### ISSUE TITLE
Wrong link?

### ISSUE THREAD

**Issue by cfelde** [James-Sangalli/eth-allowance#2]
https://github.com/James-Sangalli/eth-allowance/blob/36a8abf481a65267deef0794e7942236a58bb155/index.js#L136

Shouldn't this be:

`<div class="grid-items"><a href=${etherscanURL + txs[index].approved}>${txs[index].approved}</a></div>`

**Comment by JamesANZ** [comment]
https://github.com/James-Sangalli/eth-allowance/commit/a3f71e7108b731dd2de8f1d55b9b7daf2467b0ce

cheers mate, thanks for spotting!
