### ISSUE TITLE
Its a scam, please help me

### ISSUE THREAD

**Issue by vinztk23** [James-Sangalli/eth-allowance#38]
0xFA02917ddB9C4a14a64bea486F3cb5bF55780D66

That address i sent or send my 0.076eth and i didnt know that was a scam.. please help me to retrieve or revoke it 0.076 eth that i sent or send to him i hope someone will help me.. that money i will spend to buy my motorcycle so i dont need to commute.. someone please help me to retrieve it..

This is my wallet address 

0x113e17bFB9Ce1FeCD812Ee6BB55f9eB291989a66

**Comment by JamesANZ** [comment]
Hi @vinztk23, sorry to hear about your loss...

This tool is unable to reverse transactions and can only help you revoke ERC20/ERC721 allowances.

**Comment by vinztk23** [comment]
Ok i thought you guys could help me on this problem.
